### ISSUE TITLE
Få styr på mapper

### ISSUE THREAD

**Issue by TotalOfferen** [andreaslorentzen/Dansk-Datahistorisk-Forening#25]
LocalMediaStorage skal ændres så der bruges en privat mappe. Mappen skal indeholde en mappe til billeder og en mappe til lydfiler.

**Comment by andreaslorentzen** [comment]
Jeg tror ikke det kan lade sig gøre med billederne, Det intent man bruger til at tage billeder med har ikke skrive adgang til det private.

Men måske kan man splitte det op, så de filer man laver på telefonen, tager billede og recorder, er i public. Og de filer der hentes fra backend kommer i en private mappe

**Comment by msondrup** [comment]
Så vidt jeg har forstået kan man bare ændre den intent man bruger til at tage billeder således at den ikke gemmer billedet men bare returnere det.
