### ISSUE TITLE
New frontpage

### ISSUE THREAD

**Issue by andreaslorentzen** [andreaslorentzen/Dansk-Datahistorisk-Forening#4]
Branch: `feature-#4`

**Comment by msondrup** [comment]
![billede 04-01-2016 11 02 26](https://cloud.githubusercontent.com/assets/9074372/12087590/7e804dfe-b2d4-11e5-965c-fd2a1eb7e51a.jpg)
Det er vist på billedet hvordan frontpage skal se ud.
